### ISSUE TITLE
Create wireframes for the new screens and page layout

### ISSUE THREAD

**Issue by shrop** [shrop/contenta_flutter#19]
Wireframes should details the following:

* Home screen with list of recipes #14
* Full recipe details screen #15 
* Favorites screen #17
* About screen #18

**Comment by shrop** [comment]
Initial wireframes to cover the 4 screens. Please provide some feedback on these. 

[Contenta Flutter.pdf](https://github.com/shrop/contenta_flutter/files/3965736/Contenta.Flutter.pdf)

**Comment by shrop** [comment]
Updated version with improved layout for the Recipe Detail Screen and fav and share action buttons.

[Contenta Flutter.pdf](https://github.com/shrop/contenta_flutter/files/3965762/Contenta.Flutter.pdf)

**Comment by shrop** [comment]
Drupal 8 Umami theme with images and other content that might be useful: çhttps://git.drupalcode.org/project/drupal/tree/8.8.x/core/profiles/demo_umami/themes/umami

**Comment by bfodeke** [comment]
This is great! Nice direction with the low fidelity wireframes

**Comment by shrop** [comment]
Thanks! I think we can further define the Recipe detail page, but maybe can be worked through directly in Flutter or Sketch, if needed.

**Comment by bfodeke** [comment]
A potential piece of data that could be added on the teaser views of the recipes would be some metadata like
* Category
* Prep Time
* Difficulty

**Comment by shrop** [comment]
I think I will add some this. Thanks @bfodeke!

**Comment by shrop** [comment]
Alright, Added Category, Time and Difficulty. The API actually has prep time and total time as separate items so I am just using the total time for now.

[Contenta Flutter.pdf](https://github.com/shrop/contenta_flutter/files/4047677/Contenta.Flutter.pdf)

**Comment by shrop** [comment]
Now that we have a good start on wireframes I am going to close this and we can re-open a new one with specific changes.

**Comment by shrop** [comment]
Pushed up the following changes to the working branch:
* Setup Provider to provide state for the navbar
* Setup body text for each page
* Titles work in the app bar with each route
* Three routes work now for Home (recipes), Favs, and About
